assetDir: static
publishDir: generated
baseURL: /

DefaultContentLanguage: en
languages:
    en:
        languageName: English
        weight: 1
    nl:
        languageName: Nederlands
        weight: 2


disableHugoGeneratorInject: true
enableRobotsTXT: true

permalinks:
  posts: /:year/:month/:title/

minificationOptions:
    KeepConditionalComments: true
    KeepEndTags: false
