assetDir: static
publishDir: generated
baseURL: /

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
    en:
        languageName: English
        weight: 1
    nl:
        languageName: Nederlands
        weight: 2

disableHugoGeneratorInject: true
enableRobotsTXT: true

permalinks:
  posts: /:year/:month/:title/

minificationOptions:
    KeepConditionalComments: true
    KeepEndTags: false
