name: build

on:
  pull_request:

jobs:

  worker:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4
    -
      name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
    -
      name: npm install
      run: npm install
    -
      name: hugo build
      run: hugo --minify --gc --config=config.yml
    -
      name: wrangler
      uses: cloudflare/wrangler-action@v3.3.1
      with:
        environment: prd
        command: build
        apiToken: ${{ secrets.CF_API_TOKEN }}
